spring:
  datasource:
    url: jdbc:h2://${DB_HOST:localhost:5432}/t1_demo
    username: postgres
    password: "0000"
    driverClassName: org.h2.Driver
  liquibase:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

integration:
  url: http://localhost:1398
  resource: /bsc-wire-mock/api/client/check
  retry-count: 3
  retry-backoff: 1000

web:
  base-url: http://localhost:8082
  resources:
    blacklist-check: /blacklist/check