spring:
  application:
    name: t1-java
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.kafka.ru.t1.java.demo.kafka.consumer.AccountConsumer: DEBUG
    #ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: t1-demo
      account-id: accountListenerId
      transaction-id: transactionListenerId
      transaction-result-id: transactionResultListenerId
      max.poll.records: 10
    producer:
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered
      metrics: t1_demo_metrics
      accounts: t1_demo_accounts
      transactions: t1_demo_transactions
      transaction_accept: t1_demo_transaction_accept
      transaction_result: t1_demo_transaction_result
    listener:
      poll-timeout: 1000